# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Shihusi
description: >- # this means to ignore newlines until "baseurl:"
  Welcome
baseurl: "" # the subpath of the site
url: "" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

# theta: bay_jekyll_theme
# remote_theme: eliottvincent/bay

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog
    - name: About

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: oyyttyyo[AT]outlook.com
      link: mailto:oyyttyyo@outlook.com
  #   - name: WeChat
  #     value: YourWeChatUsername
  #     link: "#"
  # follow:
  #   - name: Twitter
  #     link: http://twitter.com/YourTwitterUsername
  #     username: "@YourTwitterUsername"
  #   - name: Facebook
  #     link: http://facebook.com/YourFacebookUsername
  #   - name: LinkedIn
  #     link: http://linkedin.com/in/YourLinkedInUsername
  #   - name: GitHub
  #     link: http://github.com/YourGitHubUsername
  #   - name: Dribbble
  #     link: https://dribbble.com/YourDribbbleUsername
  #   - name: RSS
  #     link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
